- Cargo.toml
- src/lib.rs
`time` crate is unmaintained/deprecated.
> Replace time with chrono

- Cargo.toml
- README.md
- src/lib.rs
This pull would allow an end-user to optionally use colorized output based on the log levels.
> Adding optional colorized output

- Cargo.toml
- examples/init_with_level.rs
- src/lib.rs
Hello,
Thank you for your awesome library that makes it really easy to print debug messages. I would like to propose some changes that enable Windows console color output (tested with `cmd` and `PowerShell`).
Examples:
* **before**:
* _CMD_: ![CMD](https://i.ibb.co/KW8dPBz/2019-12-23-10-42-44.png)
* _PowerShell_: ![PowerShell](https://i.ibb.co/ckJHgq9/2019-12-23-10-43-22.png)
* **after**:
* _CMD_: ![CMD_w_patch](https://i.ibb.co/QcFryGb/2019-12-23-10-49-52.png)
* _PowerShell_: ![PowerShell_w_path](https://i.ibb.co/6Bn5rT9/2019-12-23-10-54-14.png)
Also, I ran `rustfmt` on `src/lib.rs` file, but may revert that changes if needed.
> Enable Windows console colors

- Cargo.toml
- src/lib.rs
Disabling this feature removes the timestamp from the log output. This is
useful when the log output is sent to a logging gatherer which already does its
own timestamping (such as journald).
Addresses https://github.com/borntyping/rust-simple_logger/issues/9
> Add 'chrono' compile time option

- src/lib.rs
A macro for simulating env_logger behavior, which enables the user to choose log level by setting a `RUST_LOG` environment variable.
> macro init-by-env

- Cargo.toml
- src/lib.rs
Migrating to new edition is always backwards-compatible https://doc.rust-lang.org/edition-guide/editions/index.html#compatibility
> Migrate to edition = "2018"

- .github/workflows/ci.yml
- .travis.yml
- src/lib.rs
The jobs run `clippy` and `rustfmt` checks, as well as `cargo test`.
There is also a job to publish the crate. You only need to add `CRATES_TOKEN`, which is an API token from [`crates.io`](https://crates.io) to the repo secrets.
After that, to test and publish the crate run this in the local repo on the latest checkout of `master`:
```
git tag v1.0.0
git push --tags
```
> Migrate to github actions

- README.md
- examples/init.rs
- examples/init_with_level.rs
- examples/init_with_level_and_targets.rs
- src/lib.rs
This PR should allow to log only on specific log targets thus preventing any non-wanted spamming from dependencies.
Closes: #15
> Allow to log only on specific log targets

- src/lib.rs
No worries if you don't want to take this, but was easier to write the PR than to open a discussion issue.
This will warn the user if they do not call the init() method.
This patch also tweaks the docs in a few places to highlight the
need to call init.
This was motiviated because I failed to do this myself when moving
to the new API, and had a confused couple minutes :)
- reference: https://github.com/linebender/druid/pull/1218
- closes #23
> Add #[must_use] to builder methods

- src/lib.rs
Added a test, just to be sure.
Also some examples were missing a `unwrap()` after calling `init()`, fixed that too.
Closes #24.
----
I'm unsure about `with_target_levels`, since that takes a `HashMap` and we don't use that anymore (for now). Changing this is a bit tricky due to backwards compatibility. I think I could modify this into something that take an `impl IntoIterator<(String, LevelFilter)>` or the like so that the actual data structure is hidden as an implementation detail. Also I'm not sure about the semantics of that method, why does it overwrite all existing level filters instead of adding them? Can I change this or is this considered a breaking change? (@creekorful you wrote this, any opinions?)
> Match all submodules on `with_module_level`

- README.md
The provided example didn't compile because of the missing semicolon.
> Add semicolon which caused compilation errors

- src/lib.rs
These functions provide a very pleasant shortcut in the minimalist spirit of this crate.
For more advanced usages, the builder pattern is still available.
> Revert deprecation of stand-alone initialisation functions

- src/lib.rs
I want to set the default log level to INFO instead of ERROR, but I can't currently do that if I initialize SimpleLogger using `from_env`.  I added a new function, `from_env_or`, that lets me override the default log level.
> Add SimpleLogger::from_env_or

- src/lib.rs
Timestamps are useful when debugging, but when the program is executed from systemd, journald automatically adds timestamps to the lines, so one gets duplicate timestamps.
This adds an option to turn timestamps off without having to recompile with a different feature set.
> Add an option to control whether timestamps are to be printed or not.

- Cargo.toml
- README.md
Since https://github.com/borntyping/rust-simple_logger/pull/10 is possible to disable colorized output **and** timestamps, with this new addition it will be possible to choose disabling one while still keeping the other one.
> Adding the hability to choose wich feature to enable

- Cargo.toml
- src/lib.rs
Low hanging fruit to address #21. Usually it is ok to decide at compile time where log output shall go.
> Use a 'stderr' feature to target log output to stderr

- Cargo.toml
- src/lib.rs
The reason for this pull request is the recent security advisory, [RUSTSEC-2020-0159](https://rustsec.org/advisories/RUSTSEC-2020-0159). This issue detected a potential segfault in `localtime_r` invocations, and given the `chrono` crate's lack of maintenance, the `time` crate, which fixed the issue, is now the preferred crate for datetime offsets and formatting.
The format used is still identical to the one achieved via `chrono`, but this implementation also prevents the issues caused by RUSTSEC-2020-0159, which were failing CI/CL actions in many repositories dependent upon `rust-simple_logger`.
The changes should still work in a no_alloc, no_std situation as expected.
(note: yes I see that I did a typo and put RUSTSEC-2021 instead of RUSTSEC-2020 in the commit. oops)
> Exchanged `chrono` Dependency for Equal Implementation Using The Still-Maintained `time` Crate

- Cargo.toml
Hi!
I have noticed that after commits, which replaces `chrono` dependency with `time`, logger does not print timestamps by default.
In this https://github.com/borntyping/rust-simple_logger/blob/main/src/lib.rs#L37 line, `chrono` feature-gate was used before dependency changes. Now it is `timestamps`.
So I just try to actualize default feature gates in project manifest.
> Try to fix accidentally disabled default timestamps feature

- .github/workflows/ci.yml
- Cargo.toml
- examples/timestamps_local.rs
- examples/timestamps_utc.rs
- src/lib.rs
This sidesteps issues users are having when using local times in
conditions where the `time` crate cannot safely get the local time.
Thanks to @uggla and @rye.
> Add options to use UTC timestamps

- Cargo.toml
The 2.0 release of colored has only a minor API change that doesn't
affect its usage in this crate:
https://github.com/mackwic/colored/blob/v2.0.0/CHANGELOG.md
> upgrade to colored 2.0

- src/lib.rs
I had some trouble with calling the `env` method _before_ the `with_level` method, since I presumed this worked like other builder structs where the order of arguments didn't really matter.
> doc: call env after with_level

- src/lib.rs
Hi,
First of all thanks for the library.
There was an issue when having colored output on Linux(Manjaro Linux with KDE to be specific), where coloured outputs had mis-padded logging
The issue came about with how coloring is done on Linux, i.e we add special characters in the command line, e.g printing color red would add `\033[39m`,
Later on, when you tried to format the message with appropriate padding, for log levels
```rust
let message = format!(
"{}{:<5} [{}{}] {}",
timestamp,
level_string,
target,...);
```
The colored log levels would not be padded because the string is  longer than 5 characters, hence the misalignment above.
The fix was to simply do the padding before the coloring which fixes that misalignment,
now with this pr the printed output looks like
This is now in tandem …
> Ensure log levels are appropriately padded even on coloured outputs.

- Cargo.toml
- src/lib.rs
On Windows, since winapi [winapi](https://github.com/retep998/winapi-rs) is not maintained anymore and microsfot has an official api for internal links, I think it's a good idea to switch to this api [Windows API](https://docs.microsoft.com/en-us/windows/).
What do you think about it ?
> Adopt windows-sys

- README.md
- examples/timestamps_format.rs
- src/lib.rs
Added `with_custom_timestamps` to customize timestamps format.
> Customizable timestamps format

- Cargo.toml
- src/lib.rs
I replaced the use of atty by the just introduced [IsTerminal](https://doc.rust-lang.org/std/io/trait.IsTerminal.html) in std Rust.
The downside is, that this bumps MSRV to 1.70.0 but only for Windows targets which use the colored feature.
But for people who do not need or want to use the colored feature of simple_logger, this would completely remove the dependency on atty which is not maintained any more as mentioned e.g. in #74
> replace dependency to atty for windows targets by std implementation

- Cargo.toml
Other crates are now depending on 0.48, which is not semver compatible with 0.42, resulting in cargo deny warnings.
Upgrade to the latest version of windows-sys.
> Upgrade windows-sys from 0.42 to 0.48

- src/lib.rs
Remove env_logger reference from env() method docs to avoid confusion since simple_logger does not fully support the same syntax from env_logger to on parsing RUST_LOG env var.
Fix #75
> Remove misguided env_logger reference from docs

- README.md
- src/lib.rs
My personal use case is to wrap this logger in my own logger implementation, to be able to catch log calls during testing and react to them. This PR proposes to add a `configure` method to enable users to have a completely configured instance of `SimpleLogger`. Then they can set as global logger something else that might be a wrapper around `SimpleLogger`.
Usage is simply to call `configure` instead of `init` to finish configuration of an instance of `SimpleLogger`. To avoid code duplication, `init` will internally call `configure` before `set_boxed_logger`. This means that using the chain `simpleLogger::new().configure().init()` has bad performance and would not be advised. A user would either use `configure` or `init`.
Another implentation would be to add a boolean argument to `init`, …
> add configure method, to enable users to own a valid configured instance before calling `set_boxed_logger`

- src/lib.rs
Hello,
I work with programs that pipe `stdout` often. `simple_logger` would simply not print colored output to `stderr` when that happened. This is due to [this `colored` issue](https://github.com/colored-rs/colored/issues/125).
This PR aims to fix this by implementing a variation of the `set_up_color_terminal` function, enabled when the `stderr` feature is selected on other platforms than Windows (For lack of testing environment).
> Fix stderr color dependence on stdout
